import Link from "next/link";
import { Eye, Heart, ShoppingBag, Star } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import type { MockCatalogProduct } from "@/data/mock-catalog";
import { formatTaka } from "@/lib/format";

const stockVariant = { "In stock": "success", "Low stock": "warning", "Out of stock": "danger" } as const;

function CatalogProductCard({ product }: { product: MockCatalogProduct }) {
  const href = `/products/${product.id.replace(/^mock-/, "")}`;
  return <article className="group overflow-hidden rounded-lg border border-border bg-card shadow-card transition duration-300 hover:-translate-y-1 hover:shadow-elevated"><div className="relative aspect-[4/5] overflow-hidden bg-muted"><img src={product.image} alt={`${product.name} mock product`} loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" />{product.badge ? <Badge variant="outline" className="absolute left-3 top-3 bg-card/95 shadow-sm">{product.badge}</Badge> : null}<div className="absolute right-3 top-3 flex flex-col gap-2 opacity-100 transition sm:translate-x-2 sm:opacity-0 sm:group-hover:translate-x-0 sm:group-hover:opacity-100"><Link href={href} aria-label={`Quick view ${product.name}`} className="grid size-9 place-items-center rounded-full bg-card/95 text-foreground shadow-sm transition hover:bg-arven-gold"><Eye className="size-4" aria-hidden="true" /></Link><button type="button" aria-label={`Save ${product.name}`} className="grid size-9 place-items-center rounded-full bg-card/95 text-foreground shadow-sm transition hover:bg-arven-gold"><Heart className="size-4" aria-hidden="true" /></button></div><button type="button" aria-label={`Add ${product.name} to shopping bag`} className="absolute inset-x-3 bottom-3 flex h-10 translate-y-0 items-center justify-center gap-2 rounded-md bg-arven-black text-sm font-semibold text-white shadow-md transition sm:translate-y-14 sm:group-hover:translate-y-0"><ShoppingBag className="size-4" aria-hidden="true" />Add to bag</button></div><div className="p-4 sm:p-5"><p className="text-[11px] font-bold uppercase tracking-[0.15em] text-muted-foreground">{product.brand}</p><h2 className="mt-2 text-base font-semibold leading-6"><Link href={href} className="transition hover:text-secondary">{product.name}</Link></h2><div className="mt-3 flex items-end gap-2"><p className="font-bold text-secondary">{formatTaka(product.price)}</p>{product.oldPrice ? <p className="text-sm text-muted-foreground line-through">{formatTaka(product.oldPrice)}</p> : null}</div><div className="mt-3 flex items-center justify-between gap-2"><span className="flex items-center gap-1 text-xs text-muted-foreground"><Star className="size-3.5 fill-arven-gold text-arven-gold" aria-hidden="true" />{product.rating.toFixed(1)} <span className="hidden sm:inline">({product.reviewCount})</span></span><Badge variant={stockVariant[product.stock]} className="px-2 py-0.5 text-[10px]">{product.stock}</Badge></div></div></article>;
}

export { CatalogProductCard };
