import { ArrowRight, Check, CreditCard, Instagram, ShieldCheck, Sparkles, Truck } from "lucide-react";

import { CollectionCard } from "@/components/storefront/collection-card";
import { FaqPreview } from "@/components/storefront/faq-preview";
import { ProductCard } from "@/components/storefront/product-card";
import { Reveal } from "@/components/storefront/reveal";
import { SectionHeading } from "@/components/storefront/section-heading";
import { Container } from "@/components/layout/container";
import { Section } from "@/components/layout/section";
import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import { Button } from "@/components/ui/button";
import { homepageMock } from "@/data/mock-storefront";

export default function HomePage() {
  return <><SiteHeader /><main>
    <section className="relative isolate min-h-[calc(100svh-6.5rem)] overflow-hidden bg-arven-black text-white"><img src={homepageMock.heroImage} alt="Premium brown leather shoes in an editorial setting" fetchPriority="high" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-70" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(10,10,8,0.94),rgba(10,10,8,0.7)_48%,rgba(10,10,8,0.14)),linear-gradient(0deg,rgba(10,10,8,0.35),transparent_45%)]" /><Container className="flex min-h-[calc(100svh-6.5rem)] items-end py-16 sm:py-20 lg:py-24"><Reveal className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.3em] text-arven-gold">ARVEN Leather / Bangladesh</p><h1 className="mt-5 text-balance text-4xl font-semibold leading-[1.02] sm:text-6xl lg:text-7xl">A life, well carried.</h1><p className="mt-6 max-w-xl text-base leading-8 text-white/72 sm:text-lg">Quietly exceptional leather shoes, bags, and essentials made to acquire character with every passing day.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild variant="secondary"><a href="#best-sellers">Shop the collection <ArrowRight className="size-4" aria-hidden="true" /></a></Button><Button asChild variant="outline" className="border-white/25 bg-transparent text-white hover:bg-white hover:text-arven-black"><a href="#our-story">Discover ARVEN</a></Button></div></Reveal></Container></section>
    <section className="bg-secondary py-3 text-center text-sm font-medium text-secondary-foreground"><Container className="flex flex-wrap items-center justify-center gap-x-8 gap-y-1"><span>Genuine leather</span><span className="hidden sm:inline">•</span><span>Crafted for longevity</span><span className="hidden sm:inline">•</span><span>Delivery across Bangladesh</span></Container></section>
    <Section><Container><Reveal><SectionHeading eyebrow="Curated for the season" title="A more considered way to dress." description="Objects with material presence, designed to move easily between the daily ritual and the memorable occasion." /></Reveal><div className="mt-10 grid gap-4 md:grid-cols-3"><>{homepageMock.collections.map((collection, index) => <Reveal key={collection.name} delay={index * 0.06}><CollectionCard collection={collection} priority={index === 0} /></Reveal>)}</></div></Container></Section>
    <Section tone="muted" spacing="compact"><Container><Reveal><SectionHeading eyebrow="Shop by category" title="The essentials, refined." align="center" /></Reveal><div className="mt-10 grid grid-cols-2 gap-3 lg:grid-cols-4">{homepageMock.categories.map((category, index) => <Reveal key={category.name} delay={index * 0.05}><CollectionCard collection={category} /></Reveal>)}</div></Container></Section>
    <Section id="best-sellers"><Container><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><Reveal><SectionHeading eyebrow="Most loved" title="The pieces people return to." /></Reveal><Button asChild variant="link"><a href="#shop">View all pieces <ArrowRight className="size-4" aria-hidden="true" /></a></Button></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{homepageMock.bestSellers.map((product, index) => <Reveal key={product.name} delay={index * 0.05}><ProductCard product={product} priority={index < 2} /></Reveal>)}</div></Container></Section>
    <section className="relative isolate overflow-hidden bg-arven-black py-20 text-white sm:py-28"><img src={homepageMock.bannerImage} alt="Leather shoe craftsmanship" loading="lazy" decoding="async" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-45" /><div className="absolute inset-0 -z-10 bg-arven-black/65" /><Container><Reveal className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.26em] text-arven-gold">The ARVEN standard</p><h2 className="mt-4 text-balance text-4xl font-semibold leading-tight sm:text-5xl">Made for the years ahead, not a single season.</h2><p className="mt-5 text-base leading-8 text-white/70">A considered edit of honest materials, purposeful details, and timeless silhouettes.</p><Button asChild variant="secondary" className="mt-8"><a href="#our-story">Read our story <ArrowRight className="size-4" aria-hidden="true" /></a></Button></Reveal></Container></section>
    <Section id="new-arrivals"><Container><Reveal><SectionHeading eyebrow="Just arrived" title="New forms, the same point of view." description="Fresh mock arrivals with the quietly confident ARVEN finish." align="center" /></Reveal><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{homepageMock.newArrivals.map((product, index) => <Reveal key={product.name} delay={index * 0.05}><ProductCard product={product} /></Reveal>)}</div></Container></Section>
    <Section tone="muted"><Container><Reveal><SectionHeading eyebrow="Why ARVEN" title="Luxury that earns its place." align="center" /></Reveal><div className="mt-10 grid overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{homepageMock.trust.map(({ title, text, icon: Icon }, index) => <Reveal key={title} delay={index * 0.05} className="bg-background"><article className="h-full p-6 sm:p-7"><div className="grid size-11 place-items-center rounded-md bg-arven-black text-arven-gold"><Icon className="size-5" aria-hidden="true" /></div><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article></Reveal>)}</div></Container></Section>
    <Section id="our-story"><Container><div className="grid gap-10 lg:grid-cols-2 lg:items-center lg:gap-16"><Reveal><div className="overflow-hidden rounded-lg bg-muted"><img src={homepageMock.storyImage} alt="ARVEN leather details" loading="lazy" decoding="async" className="aspect-[4/5] h-full w-full object-cover" /></div></Reveal><Reveal><SectionHeading eyebrow="The ARVEN story" title="A quieter expression of luxury." description="ARVEN is imagined for people who value how something is made as much as how it looks. Every mock collection is built around warmth, proportion, and enduring use." /><ul className="mt-7 space-y-3 text-sm text-muted-foreground">{["Material-led design", "Timeless, useful silhouettes", "Made with Bangladesh in mind"].map((item) => <li key={item} className="flex items-center gap-3"><Check className="size-4 text-secondary" aria-hidden="true" />{item}</li>)}</ul><Button asChild className="mt-8"><a href="#process">Our process <ArrowRight className="size-4" aria-hidden="true" /></a></Button></Reveal></div></Container></Section>
    <Section id="process" tone="muted"><Container><div className="grid gap-10 lg:grid-cols-2 lg:items-center lg:gap-16"><Reveal className="lg:order-2"><div className="overflow-hidden rounded-lg bg-arven-black"><img src={homepageMock.processImage} alt="Leather craft process" loading="lazy" decoding="async" className="aspect-[4/5] h-full w-full object-cover opacity-85" /></div></Reveal><Reveal className="lg:order-1"><SectionHeading eyebrow="The leather process" title="From material to memory." description="The enduring appeal of leather comes from patience: selecting it carefully, shaping it with intention, and finishing it with restraint." /><ol className="mt-8 space-y-5">{homepageMock.process.map((step, index) => <li key={step} className="flex gap-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-secondary text-sm font-bold text-secondary-foreground">0{index + 1}</span><div><h3 className="font-semibold">{step}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">A deliberate stage in the mock ARVEN craft narrative.</p></div></li>)}</ol></Reveal></div></Container></Section>
    <Section className="bg-arven-black text-white"><Container><Reveal><SectionHeading eyebrow="Customer notes" title="Quietly loved, daily lived." description="Selected mock testimonials for the storefront presentation." align="center" className="text-white [&_p]:text-white/62" /></Reveal><div className="mt-10 grid gap-5 md:grid-cols-3">{homepageMock.testimonials.map((testimonial, index) => <Reveal key={testimonial.name} delay={index * 0.06}><article className="h-full rounded-lg border border-white/10 bg-white/[0.04] p-6 sm:p-7"><Sparkles className="size-5 text-arven-gold" aria-hidden="true" /><blockquote className="mt-5 text-base leading-8 text-white/78">“{testimonial.quote}”</blockquote><div className="mt-7 border-t border-white/10 pt-4"><p className="font-semibold">{testimonial.name}</p><p className="mt-1 text-sm text-white/48">{testimonial.location}</p></div></article></Reveal>)}</div></Container></Section>
    <Section><Container><Reveal><SectionHeading eyebrow="From the studio" title="Follow the material." description="A mock social edit of the leather, the detail, and the daily carry." align="center" /></Reveal><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{homepageMock.instagram.map((image, index) => <Reveal key={image} delay={index * 0.04}><a href="#instagram" className="group relative block aspect-square overflow-hidden rounded-md bg-muted"><img src={image} alt={`ARVEN mock gallery image ${index + 1}`} loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><span className="absolute inset-0 grid place-items-center bg-arven-black/45 opacity-0 transition group-hover:opacity-100"><Instagram className="size-5 text-white" aria-hidden="true" /></span></a></Reveal>)}</div></Container></Section>
    <section className="bg-secondary py-16 text-secondary-foreground sm:py-20"><Container><Reveal className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[0.25em] text-arven-black/65">The ARVEN Letter</p><h2 className="mt-4 text-balance text-3xl font-semibold sm:text-5xl">The next piece might be the one you keep.</h2><p className="mt-5 text-sm leading-7 text-arven-black/70 sm:text-base">New arrivals, private edits, and notes on living well with leather.</p><form className="mx-auto mt-8 flex max-w-lg flex-col gap-3 sm:flex-row" aria-label="Homepage newsletter subscription"><label className="sr-only" htmlFor="homepage-email">Email address</label><input id="homepage-email" type="email" placeholder="Your email address" className="h-12 min-w-0 flex-1 rounded-md border border-arven-black/15 bg-white/90 px-4 text-sm text-foreground outline-none focus:ring-2 focus:ring-arven-black/20" /><Button type="button" className="bg-arven-black text-white hover:bg-arven-black/90">Subscribe</Button></form></Reveal></Container></section>
    <Section spacing="compact"><Container><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><Reveal><SectionHeading eyebrow="Questions, answered" title="Before your first ARVEN piece." /><Button asChild variant="link" className="mt-6"><a href="#faq">View all FAQs <ArrowRight className="size-4" aria-hidden="true" /></a></Button></Reveal><Reveal><FaqPreview faqs={homepageMock.faqs} /></Reveal></div></Container></Section>
    <section className="border-y border-border bg-muted/45"><Container className="grid gap-8 py-9 md:grid-cols-3 md:items-center"><div className="flex items-center gap-3"><Truck className="size-6 text-secondary" aria-hidden="true" /><div><p className="font-semibold">Delivered with care</p><p className="mt-1 text-sm text-muted-foreground">Across Bangladesh</p></div></div><div className="flex items-center gap-3"><ShieldCheck className="size-6 text-secondary" aria-hidden="true" /><div><p className="font-semibold">Easy exchange support</p><p className="mt-1 text-sm text-muted-foreground">For a confident first order</p></div></div><div className="flex flex-wrap items-center gap-2 md:justify-end">{homepageMock.paymentLabels.map((label) => <span key={label} className="inline-flex items-center gap-1.5 rounded-md border border-border bg-card px-3 py-2 text-xs font-semibold text-muted-foreground"><CreditCard className="size-3.5 text-secondary" aria-hidden="true" />{label}</span>)}</div></Container></section>
  </main><SiteFooter /></>;
}
